[workspace]

members = [
    "aoc_helper",
    "aoc1",
    "aoc2",
    "aoc3",
    "aoc4",
    "aoc5",
    "aoc6",
    "aoc7",
    "aoc8",
    "aoc9",
    "aoc10",
    "aoc11",
    "aoc12",
    "aoc12_2",
    "aoc13",
    "aoc14",
    "aoc15",
    "aoc16",
    "aoc17"
]