[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_helper = { version = "0.1.0", path = "../aoc_helper" }
float-cmp = "0.9.0"
regex = "1.10.2"
